#!/bin/bash

#   Internal use only

cd psycho

cp changelog ~/git/3ppq/wip/

echo '
#include "VERSION"
SUBST(_CurVers_)(VERSION)
SUBST(_CurYrs_)(YEARS)
' | gcc -E - | grep -v '^#' | sed 's/"//g' > ~/git/3ppq/wip/release.yo

cd ..
git co gh-pages

