#ifndef INCLUDED_REPORT_
#define INCLUDED_REPORT_

#include <string>

class WIPdata;

class Report
{
    std::string d_pidCid;
    std::string d_csvName;

    uint32_t d_from;
    std::string d_psychEmail;

    std::string d_eps;              // eps generated by gnuplot 
    std::string d_scores;           // scores table generated by gnuplot
        
    public:
        Report(WIPdata const &wipData);
        void fsplot();

        void generate();

    private:
};
        
#endif
