//                     usage.cc

#include "main.ih"

void usage(std::string const &progname)
{
    cout << "\n" <<
    progname << " by " << author << "\n" <<
    progname << " V" << version << " " << years << "\n"
    "\n"
    "Usage: " << progname << " csv gnuplotIn gnuplotData scores\n"
    "Where:\n"
    "   [options] - optional arguments (short options between parentheses):\n"
    "      --help (-h)      - provide this help\n"
    "      --version (-v)   - show version information and terminate\n"
    "   csv                 - path to the csv file produced by `form'\n"
    "   gnuplotIn           - path to the gnuplot input file\n"
    "   gnuplotData         - path to the produced gnuplot data file\n"
    "   scores              - scores table produced by " << progname << "\n"
    "   (the plot generated by gnuplot is written to the file specified in\n"
    "    gnuplotIn).\n"
    "\n";
}
