#!/bin/bash

if [ $# -eq 0 ] ; then
    echo "
First argument must be the target directory, created if non-existing.
Run this script as the destination user from the location where this script
is located. 
The destination user should be a member of the group www-data.
The target directory may be specified as a relative or absolute path.

"
    exit 1
fi

website=$1

if [ $website == "website.skel" ] ; then
    echo "website.skel is reserved. Use another name"
    exit 1
fi

if [ ! -e website.skel/bin/form ] ; then
    cd support
    icmbuild || exit 1

    cd ../form
    icmbuild || exit 1

    icmbuild install program ../website.skel/bin/form
    cd ..
fi

website=`realpath ${website}`

mkdir -p ${website}

if [ ! -d ${website} ] ; then
    echo "no directory \`${website}'"
    exit 1
fi

cd website.skel
tar cf - --exclude .filler --exclude '*/ORG' --exclude README . | 
                                            (cd ${website}; tar xf -)

cd ${website}

touch log

chmod o-rwx .                       # no access except for www-data and user

chgrp -fR www-data .
chmod -fR g+r .

chmod -fR g+w data log
chmod -f g+s data

