#!/bin/bash

if [ $# -eq 0 ] ; then
    echo "
Provide initial option  --all to call ./build for all 3ppq programs.

First argument must be the website's base directory, created if non-existing.
Below this base directory directories like ./www are defined. The website's
base path must also be specified in apache's configuration, see 
website.skel/apache/config for an example.

Run this script as the destination user from the location where this script
is located. 

The destination user should be a member of the group www-data.
The target directory may be specified as a relative or absolute path.

"
    exit 1
fi

if [ "$1" == "--all" ] ; then
    all=1
    shift
else
    all=0
fi

base=`pwd`

website=$1

if [ $website == "website.skel" ] ; then
    echo "website.skel is reserved. Use another name"
    exit 1
fi

try()
{
    $* && return

    echo "Error: failed to $*"
    exit 1
}

website=`realpath ${website}`

mkdir -p ${website}

if [ ! -d ${website} ] ; then
    echo "no directory \`${website}'"
    exit 1
fi

if [ ${all} -eq 1 ] ; then
    try cd support
    icmbuild

    for program in form fsplot psychrm psychrecords
    do
        echo "
        ./build ${program}"
        try cd ${base}/${program}
        ./build
    done
elif [ ! -e ${website}/bin/form ] ; then
    try cd support
    icmbuild

    try cd ${base}/form
    ./build

    icmbuild install program ${website}/bin/form

    [ -e ${website}/bin/form ] || exit 1
fi

try cd ${base}

if [ ! -e ${website}/bin/fsplot ] ; then
    try cd fsplot
    ./build || exit 1

    icmbuild install program ${website}/bin/fsplot
    [ -e ${website}/bin/fsplot ] || exit 1
fi

try cd ${base}

for program in form fsplot
do
    if [ ${program}/tmp/bin/binary -nt ${website}/bin/${program} ] ; then
        cp ${program}/tmp/bin/binary ${website}/bin/${program}
    fi
done

try cd website.skel
tar cf - --exclude-from exclude . | (cd ${website}; tar xf -)

try cd ${website}

try touch log

chgrp -fR www-data .

try chmod o-rwx .               # no access except for www-data and
                                # user

                                # www-data may write log and some directories
chmod -fR g+w log data tmp reports

echo ready.
