#!/bin/bash

if [ $# -eq 0 ] ; then
    echo "
First argument must be the target directory, created if non-existing.
Run this script as the destination user from the location where this script
is located. 
The destination user should be a member of the group www-data.
The target directory may be specified as a relative or absolute path.

"
    exit 1
fi

base=`pwd`

website=$1

if [ $website == "website.skel" ] ; then
    echo "website.skel is reserved. Use another name"
    exit 1
fi

try()
{
    $* && return

    echo "Error: failed to $*"
    exit 1
}

website=`realpath ${website}`

mkdir -p ${website}

if [ ! -d ${website} ] ; then
    echo "no directory \`${website}'"
    exit 1
fi

if [ ! -e ${website}/bin/form ] ; then
    cd support
    icmbuild || exit 1

    cd ${base}/form
    icmbuild || exit 1

    icmbuild install program ${website}/bin/form
fi

try cd ${base}

if [ ! -e ${website}/bin/fsplot ] ; then
    cd ../fsplot
    icmbuild || exit 1

    icmbuild install program ${website}/bin/fsplot
fi

try cd ${base}

for program in form fsplot
do
    if [ ${program}/tmp/bin/binary -nt ${website}/bin/${program} ] ; then
        cp ${program}/tmp/bin/binary ${website}/bin/${program}
    fi
done

try cd website.skel
tar cf - --exclude .filler --exclude '*/ORG' --exclude README . |
                                            (cd ${website}; tar xf -)

try cd ${website}

try touch log

chgrp -fR www-data . > /dev/null 2>&1

try chmod o-rwx .               # no access except for www-data and
                                # user

try chmod -fR g+w log           # www-data may write log

                                # www-data may write several directories
try chmod g+w data tmp www/results htaccess        

echo ready.
