#!/bin/bash

if [ ! -e website ] ; then
    echo the directory website must exist
    exit 1
fi

cd website 

mkdir -p bin js css html data images www mail
touch log

chgrp -fR .
chmod -fR g+r .

chmod -f g+w data log
chmod -f g+s data
