#!/bin/bash

if [ $# -eq 0 ] ; then
    echo "provide path to the website's base directory (containing ./www)"
    exit 1
fi

base=`pwd`

cd support
icmbuild
cd ${base}/form
./build
cd ${base}

cp form/tmp/bin/binary $1/bin/form

